model: ['/content/drive/MyDrive/SATHYA-NMT/data/models/ta2knrnn_step_50000.pt','/content/drive/MyDrive/SATHYA-NMT/data/models/ta2knrnn_step_48000.pt','/content/drive/MyDrive/SATHYA-NMT/data/models/ta2knrnn_step_44000.pt']
src: /content/drive/MyDrive/SATHYA-NMT/data/ta-kn/testspm.ta
n_best: 1
min_length: 0
max_length: 150
beam_size: 5
verbose: true
report_time: true
output: data/ta-kn/testoutputspm.kn