## Where the samples will be written
save_data: data/ta-kn/
## Where the vocab(s) will be written
src_vocab: data/models/spm_model.bpe.ta.kn.vocab
share_vocab: true
# Corpus opts:
data:
    corpus_0:
        path_src: data/ta-kn/train.ta
        path_tgt: data/ta-kn/train.kn
        transforms: [sentencepiece]
    valid:
        path_src: data/ta-kn/val.ta
        path_tgt: data/ta-kn/val.kn
        transforms: [sentencepiece]

### Transform related opts:
#### Subword
src_subword_model: data/models/spm_model.bpe.ta.kn.model
src_subword_nbest: 1
src_subword_alpha: 0.0
#### Filter
src_seq_length: 150
tgt_seq_length: 150

# silently ignore empty lines in the data
skip_empty_level: silent
n_sample: -1