# General opts
data:
    corpus_0:
        path_src: data/en-hi/train.hi
        path_tgt: data/en-hi/train.en
        transforms: [sentencepiece]
    valid:
        path_src: data/en-hi/val.hi
        path_tgt: data/en-hi/val.en
        transforms: [sentencepiece]

### Transform related opts:
#### Subword
share_vocab: true
src_vocab: data/models/spm_model.bpe.en.hi.vocab

src_subword_model: data/models/spm_model.bpe.en.hi.model
src_subword_nbest: 1
src_subword_alpha: 0.0
#### Filter
src_seq_length: 250
tgt_seq_length: 250

# silently ignore empty lines in the data
skip_empty_level: silent


save_model: data/models/hi2en
keep_checkpoint: 50
save_checkpoint_steps: 10000
average_decay: 0.0005
seed: 1234
report_every: 100
train_steps: 50000
valid_steps: 5000

# Batching
queue_size: 10000
bucket_size: 32768
world_size: 4
gpu_ranks: [0, 1, 2, 3]
batch_type: "tokens"
batch_size: 4096
valid_batch_size: 16
batch_size_multiple: 1
max_generator_batches: 0
accum_count: [3]
accum_steps: [0]

# Optimization
model_dtype: "fp32"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model Vaswani et al. 
encoder_type: transformer
decoder_type: transformer
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]
share_decoder_embeddings: true
share_embeddings: true


